#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
docker push registry.heroku.com/eficode-haku/web
(
  echo "$DOCKER_USERNAME"
  echo "$DOCKER_PASSWORD"
) | heroku login
heroku container:release web --app eficode-haku
